"""plotting of clusters generated by kmeans clustering"""
from usage import dataset, centroids, cluster_assignments
import matplotlib.pyplot as plt
import numpy as np

# scatter clusters
for cluster, _ in enumerate(centroids):
    cluster_instances = dataset[np.nonzero(cluster_assignments[:, 0].A == cluster)[0]]
    plt.scatter(cluster_instances[:, 0], cluster_instances[:, 1])

# display centroids
plt.scatter(centroids.A[:, 0], centroids.A[:, 1], color='red', marker='+', s=100)

plt.show()