"""plotting of clusters generated by kmeans clustering"""
import matplotlib.pyplot as plt
import numpy as np

# kmeans clustering
from usage import dataset, centroids, cluster_assignments
fig = plt.figure()
ax = fig.add_subplot(111)

# scatter clusters
for cluster, _ in enumerate(centroids):
    cluster_instances = dataset[np.nonzero(cluster_assignments[:, 0].A == cluster)[0]]
    ax.scatter(cluster_instances[:, 0], cluster_instances[:, 1])

# display centroids
ax.scatter(centroids.A[:, 0], centroids.A[:, 1], color='red', marker='+', s=100)

# bisecting kmeans clustering
from usage import dataset_2, centroids_2, cluster_assignments_2
fig_2 = plt.figure()
ax_2 = fig_2.add_subplot(111)

for cluster, _ in enumerate(centroids_2):
    cluster_instances = dataset_2[np.nonzero(cluster_assignments_2[:, 0].A == cluster)[0]]
    ax_2.scatter(cluster_instances[:, 0], cluster_instances[:, 1])

# display centroids
ax_2.scatter(centroids_2.A[:, 0], centroids_2.A[:, 1], color='red', marker='+', s=100)

plt.show()